### ISSUE TITLE
UTF8 characters in cookies?

### ISSUE THREAD

**Issue by bquorning** [whitequark/rack-utf8_sanitizer#27]
> Rack::UTF8Sanitizer is a Rack middleware which cleans up invalid UTF8 characters in request URI and headers.

How about invalid UTF8 characters in request cookies – could/should they be cleaned up as well?

**Comment by bf4** [comment]
Just curious what sorts of failures this has caused for you. Could you share an example?

**Comment by bquorning** [comment]
I can share two different examples. The first happens (apparently) when an exception has occurred and the Rollbar gem is preparing to catch it:

```
/gems/rollbar-1.2.13/lib/rollbar/request_data_extractor.rb:161 in "=~"
/gems/rollbar-1.2.13/lib/rollbar/request_data_extractor.rb:161 in "block in rollbar_filtered_params"
/gems/rollbar-1.2.13/lib/rollbar/request_data_extractor.rb:160 in "each"
/gems/rollbar-1.2.13/lib/rollbar/request_data_extractor.rb:160 in "inject"
/gems/rollbar-1.2.13/lib/rollbar/request_data_extractor.rb:160 in "rollbar_filtered_params"
/gems/rollbar-1.2.13/lib/rollbar/request_data_extractor.rb:25 in "extract_request_data_from_rack"
/gems/rollbar-1.2.13/lib/rollbar/middleware/rails/rollbar.rb:37 in "fetch_scope"
/gems/rollbar-1.2.13/lib/rollbar/middleware/rails/rollbar.rb:18 in "call"
```

The second failure type happens when I try to verify a malformed session cookie:
```
/gems/activesupport-4.1.9/lib/active_support/core_ext/object/blank.rb:117 in "==="
/gems/activesupport-4.1.9/lib/active_support/core_ext/object/blank.rb:117 in "blank?"
/gems/activesupport-4.1.9/lib/active_support/message_verifier.rb:36 in "verify"
```

I’m not really sure whether this is caused by me inadvertently putting malformed data into my user’s cookies (silly me), of if some users the users themselves are responsible.

I also don’t know whether it should really be the responsibility of the libraries (Rollbar and ActiveSupport) trying to read those cookies, to ensure that the string is in a format that they can work with.

**Comment by whitequark** [comment]
This looks like something within the domain of rack-utf8_sanitizer.

**Comment by bf4** [comment]
Do you have any bad data we can use to write a failing test?  Bonus if
you write it :)

**Comment by mvgijssel** [comment]
+1

**Comment by bf4** [comment]
@mvgijssel can you elaborate?

**Comment by mvgijssel** [comment]
Sorry about being blunt, but would really love this addition! I use the gem extensively to get rid of all the ''ArgumentError: invalid byte sequence in UTF-8". A few cases still have this issue due to cookies and multipart/form-data headers.

**Comment by bf4** [comment]
Do you have code that can reproduce the error?
