### ISSUE TITLE
Rack lock

### ISSUE THREAD

**Issue by mensfeld** [whitequark/rack-utf8_sanitizer#33]
Does it really need to have  gem.add_dependency "rack", '~> 1.0'? It blocks using this with Rails 5 that require Rack 2

**Comment by whitequark** [comment]
Well I dunno, Rack 2 was released like a week ago. Someone should test it...

**Comment by whitequark** [comment]
There isn't a proper release of Rack 2, only an alpha, and correspondingly there are no release notes that list the breaking changes.

**Comment by whitequark** [comment]
Hm, well, seems safe. I've pushed 1.3.2.

**Comment by mensfeld** [comment]
Thank you a lot!
