### ISSUE TITLE
What about multipart/form-data encoding?

### ISSUE THREAD

**Issue by Antiarchitect** [whitequark/rack-utf8_sanitizer#34]
My API consumers send me POST/PUT/PATCH with multipart/form-data Content-Type. Can it be also sanitized with ease of adding additional_content_types: ['multipart/form-data'](think not) and how can we support this type of encoding?

**Comment by whitequark** [comment]
You'd need to parse the multipart/form-data body and for every part, sanitize it according to its content-type. This shouldn't be very hard.

**Comment by Antiarchitect** [comment]
But what the place I should do this parsing? Seems like this gem is a good place for that.

**Comment by whitequark** [comment]
Yes

**Comment by Antiarchitect** [comment]
Ok, will try to make Pull Request in a few days or so.
