### ISSUE TITLE
Does it sanitize the request body (e.g. JSON)?

### ISSUE THREAD

**Issue by collimarco** [whitequark/rack-utf8_sanitizer#46]
In our Rails application we sometimes get this error when we try to save a record:

> ArgumentError (invalid byte sequence in UTF-8)

This in caused by invalid characters contained in the  request body. Does `rack-utf8_sanitizer` sanitize the request body for `application/json`?

I ask this because the description says:

 > cleans up invalid UTF8 characters in **request URI** and **headers**.

However you then say:

> The default content types to be sanitized are 'text/plain', 'application/x-www-form-urlencoded', 'application/json', 'text/javascript'.

**Comment by bf4** [comment]
Yes. see https://github.com/whitequark/rack-utf8_sanitizer/blob/d1ec18f46d2d65fe5e45da7e7c63cfaf0802de2c/lib/rack/utf8_sanitizer.rb#L99

**Comment by collimarco** [comment]
> Yes. 

Ok great! Probably you should update the description of the project, because it is not clear that it also sanitize the _HTTP body_ (you only mention _request URI_ and _headers_)

**Comment by bf4** [comment]
PRs welcome

**Comment by zachmccormick** [comment]
Made a PR in #47 to update the readme so that the first paragraph reflects this reality. I also was misled by that first paragraph
