### ISSUE TITLE
How to prevent to sanitize for the body of the request?

### ISSUE THREAD

**Issue by kyleevert** [whitequark/rack-utf8_sanitizer#49]
Hello.
After adding this gem, the body of the request is also sanitized, too.
Is there any configuration to block to sanitize the body of the request?
I think it can't be done by `only` or `except` option.

**Comment by bf4** [comment]
@kyleevert you want to prevent the body of the request from being sanitized?

probably you'll need to look at the code. I don't think myself or @whitequark use the gem anymore and haven't for years.

**Comment by kyleevert** [comment]
@bf4 
Thank you for your quick reply.
Yes, I want to prevent the body of the request from being sanitized.
I have already checked the code, but I can't find to sanitize the body at any place of the codes.

**Comment by bf4** [comment]
@kyleevert the rack request body is rack.input

**Comment by kyleevert** [comment]
@bf4 
Thank you for your help.
