### ISSUE TITLE
warning in ruby 2.7.0

### ISSUE THREAD

**Issue by huobazi** [whitequark/rack-utf8_sanitizer#51]
```bash
/Users/xx/.gem/ruby/2.7.0/gems/rack-utf8_sanitizer-1.6.0/lib/rack/utf8_sanitizer.rb:234: warning: URI.escape is obsolete
```

**Comment by bf4** [comment]
@huobazi in what context are you on Ruby 2.7 and using this gem? I haven't used it for years

**Comment by AlexWayfer** [comment]
> @huobazi in what context are you on Ruby 2.7 and using this gem? I haven't used it for years

When clients send corrupted data. I don't remember exactly cases, but I guess something like with one character after `%` instead of 2.

**Comment by driv3r** [comment]
From what I saw there's no easy replacement, except just in-lining the method itself from [rfc2396 parser](https://github.com/ruby/ruby/blob/ruby_2_7/lib/uri/rfc2396_parser.rb#L283:L313)

It's really weird that method is deprecated without any real replacement. On the other hand it's more or less just a `gsub` :thinking:

**Comment by AlexWayfer** [comment]
> From what I saw there's no easy replacement

Yes, I agree.

> It's really weird that method is deprecated without any real replacement.

Yes, that's our Ruby…

> On the other hand it's more or less just a `gsub` :thinking:

I thought about simple self-implementation of method content. Like… why not.

**Comment by driv3r** [comment]
@AlexWayfer In the end we are testing our apps without this middleware, as we also started getting weird errors like `#<Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT>` which we didn't had before

**Comment by AlexWayfer** [comment]
I've found a possible work-around and created #53.
