### ISSUE TITLE
#<Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT>

### ISSUE THREAD

**Issue by theghall** [whitequark/rack-utf8_sanitizer#54]
I get the following error: #<Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT>.  The input getting sanitized contains the extended ASCII character 127 (â). 

I am using rack v2.2.2 and rack-utf8_sanitizer v1.7.0. It does not happen with rack-utf8_sanitizer v1.3.2

It happens here: utf8_sanitizer.rb:263:in `start_with?'

**Comment by theghall** [comment]
It may be related to upgrading to Ruby 2.7.0 as it does not appear to happen with 1.7.0 running under Ruby 2.6.5.

**Comment by bf4** [comment]
it could be your rack version. there was a regression in rack related to encodings iirc

https://github.com/rack/rack/commit/8c62821f4a464858a6b6ca3c3966ec308d2bb53e

https://github.com/rack/rack/commit/8c62821f4a464858a6b6ca3c3966ec308d2bb53e#diff-4fc9bc1f7d91630f4f9f47fc6663f3f7R195

see https://github.com/rack/rack/pull/1486

**Comment by theghall** [comment]
> it could be your rack version. there was a regression in rack related to encodings iirc
> 
> [rack/rack@8c62821](https://github.com/rack/rack/commit/8c62821f4a464858a6b6ca3c3966ec308d2bb53e)
> 
> [rack/rack@8c62821#diff-4fc9bc1f7d91630f4f9f47fc6663f3f7R195](https://github.com/rack/rack/commit/8c62821f4a464858a6b6ca3c3966ec308d2bb53e#diff-4fc9bc1f7d91630f4f9f47fc6663f3f7R195)
> 
> see [rack/rack#1486](https://github.com/rack/rack/pull/1486)

Sounds right.  Even if I specify the charset as iso-8859-1, it still does not work.

**Comment by bf4** [comment]
@theghall do you really need this lib? If you just want something to safely handle string conversions I have a gem for that.

**Comment by theghall** [comment]
I upgraded to ruby 2.7.1 and the issue appears to have been resolved.
