### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by anitsirc** [whitequark/rack-utf8_sanitizer#69]
Hi 👋 

Is it possible to get a new release with the [allow Rack version 3 change](https://github.com/whitequark/rack-utf8_sanitizer/commit/51d359b34754be5c407a074af0d1b95be00c80fc)? 

Diff of unreleased changes: https://github.com/whitequark/rack-utf8_sanitizer/compare/v1.7.0...master

Thanks in advanced!

**Comment by whitequark** [comment]
Released 1.8.0
